language: python

python:
  - "3.9"

addons:
  firefox: latest

install:
  - pip install -r requirements.txt

before_script:
  - install-webdrivers --path webdrivers

env:
  global:
    - DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
  - flake8 --ignore E501
  - isort . --check
