# Generated by Django 3.1.2 on 2020-11-23 15:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, null=True)),
                ("code", models.CharField(max_length=13, unique=True)),
                ("brand", models.CharField(max_length=100, null=True)),
                ("photo_url", models.TextField(null=True)),
                ("product_url", models.TextField(null=True)),
                ("nutrition_grade", models.CharField(max_length=1)),
                ("energy_100g", models.IntegerField(default=0)),
                ("fat", models.IntegerField(default=0)),
                ("saturates", models.IntegerField(default=0)),
                ("carbohydrate", models.IntegerField(default=0)),
                ("sugars", models.IntegerField(default=0)),
                ("protein", models.IntegerField(default=0)),
                ("fiber", models.IntegerField(default=0)),
                ("salt", models.IntegerField(default=0)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="product", to="food_choice.Category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favoris",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_product",
                        to="food_choice.product",
                    ),
                ),
                (
                    "substitute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_substitute",
                        to="food_choice.product",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="favoris",
            constraint=models.UniqueConstraint(
                fields=("product", "substitute", "owner"),
                name="unique_user_favorite",
            ),
        ),
    ]
