# Generated by Django 3.1.2 on 2020-11-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_choice", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favoris",
            name="unique_user_favorite",
        ),
        migrations.AddConstraint(
            model_name="favoris",
            constraint=models.UniqueConstraint(
                fields=("product", "substitute", "owner"),
                name="unique_user_favoris",
            ),
        ),
    ]
